Repository pyenv/pyenv, pull requests merged in 2021-01, with the labels that each got.

#1781 Create pypy3.7-7.3.3-src
  plugins/python-build/share/python-build/pypy3.7-7.3.3-src
Labels: pr: new version

#1780 Create pypy3.7-7.3.3
  plugins/python-build/share/python-build/pypy3.7-7.3.3
Labels: pr: new version

#1727 Add PyPy 3.7-7.3.2 (source distribution)
  plugins/python-build/share/python-build/pypy3.7-7.3.2-src
Labels: pr: new version

#1726 Add PyPy 3.7-7.3.2 (binary distribution)
  plugins/python-build/pypy3.7-7.3.2
Labels: pr: new version

#1718 Add pypy3.7
  plugins/python-build/share/python-build/pypy3.7-7.3.2
Labels: pr: new version

#1763 Add miniconda3 4.8.2, 4.8.3, & 4.9.2
  plugins/python-build/share/python-build/miniconda3-3.7-4.8.2
  plugins/python-build/share/python-build/miniconda3-3.7-4.8.3
  plugins/python-build/share/python-build/miniconda3-3.7-4.9.2
  plugins/python-build/share/python-build/miniconda3-3.8-4.8.2
  plugins/python-build/share/python-build/miniconda3-3.8-4.8.3
  plugins/python-build/share/python-build/miniconda3-3.8-4.9.2
  plugins/python-build/share/python-build/miniconda3-3.9-4.9.2
Labels: needs attention, pr: new version

#1749 Use associative arrays for performance on bash >= 4
  libexec/pyenv-rehash
  libexec/pyenv-versions
Labels: needs attention, type: enhancement
